# Generated by Django 4.2.11 on 2025-01-11 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=30)),
                ('director', models.CharField(max_length=30)),
                ('release_year', models.CharField(max_length=30)),
                ('synopsis', models.CharField(max_length=400)),
            ],
        ),
    ]
